name: "TF PLAN"
env:             # Global variables declaration
  OWNER_NAME: "Thangadurai, Murugan"
  DATE: "16/06/2023"

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: PROVIDER
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-south-1"

    steps:
      - name: BEFORE
        run: ls -lart
      - name: GIT CHECKOUT
        uses: actions/checkout@v1
      - name: AFTER
        run: ls -lart
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: WELCOME MESSAGE
        run: |
          echo "Hello, Thangadurai! Hope you're Good!"
          echo "Printing Global env variables ${{ env.OWNER_NAME }}"
          echo "Printing Gloabl env variables ${{ env.DATE }}"
    job2:
       name: LINUX COMMANDS
       runs-on: ubuntu-latest
       needs: [job1]
       env:
          VAR1: "Job2 variable 1"
	  VAR2: "Job2 variable 2"  
      steps:
        - name: Print some messages		
          run: |
              ls -lrth
              pwd
              echo "Printing Global env variables ${{ env.OWNER_NAME }}"
              echo "Printing Gloabl env variables ${{ env.DATE }}"
              echo "CHANGE dir /demo/"
              cd demo
              ls -lrt
              echo "terraform stuff begin" 
	      echo "Printing Job level env variables ${{ env.VAR1 }}"
              echo "Printing Job level env variables ${{ env.VAR1 }}"
              echo "Taking '5' seconds break...."
              sleep 5
              terraform --version
              terraform init 
              terraform fmt 
              terraform validate
              terraform plan
