#---------------------------------------------------------------------
# GitHub Action Workflow to provision Infra in AWS cloud
#
# Version      Date        Info
# 1.0          2019        Initial Version
#
# Made by Thangadurai Murugan Copyleft (c) 2023
#---------------------------------------------------------------------
name: "TF PLAN"
env:
  OWNER_NAME      : "Thangadurai, Murugan"
  DATE            : "16/06/2023"
  AWS_REGION_NAME : "us-west-2"
  ENVIRONMENT      : "Development"

on:
  push:
    branches:
      - main

jobs:
  my_ci_pipeline:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone our repository
        uses: actions/checkout@v3
    
      - name: Configure my AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.MY_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.MY_SECRET_ACCESS_KEY }}
          aws-region           : ${{ env.AWS_REGION_NAME }}
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: ENVIRONMENT VARIABLES CHECKING
        run: |
          echo "Hello, Thangadurai! Hope you're Good!"
          echo "Project owner is ${{ env.OWNER_NAME }}"
          echo "Project created date is ${{ env.DATE }}"
          echo "Project created Environment is ${{ env.ENVIRONMENT }}"
      - name: CHANGING DIR
        run: |
          ls -lrt
          cd demo/
          ls -lrt
          terraform fmt
          terraform init
          terraform validate
          terraform plan
          echo "BASIC CHECKS OF TF IS DONE......"
