name: "TF PLAN"
env:
  OWNER_NAME: "Thangadurai, Murugan"
  DATE: "16/06/2023"

on:
  push:
    branches:
      - main

jobs:
  build:
    
    name: PROVIDER
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: "ap-south-1"

    steps:
      - name: BEFORE
        run: ls -lart
      - name: GIT CHECKOUT
        uses: actions/checkout@v1
      - name: AFTER
        run: ls -lart
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: WELCOME MESSAGE
        run: |
          echo "Hello, Thangadurai! Hope you're Good!"
          echo "Printing Global env variables ${{ env.OWNER_NAME }}"
          echo "Printing Gloabl env variables ${{ env.DATE }}"
  deploy:
       
    name: LINUX COMMANDS
    runs-on: ubuntu-latest
    needs: [build]
    env:
      VAR1: "DEV-ENV"
      VAR2: "TESTING"  
       
    steps:
      - name: Print some messages		
        run: |
          ls -lrth
          pwd
          echo "Project Owner name is: ${{ env.OWNER_NAME }}"
          echo "Project created date is: ${{ env.DATE }}"
          echo "CHANGE dir /demo/"
          cd demo
          ls -lrt
          echo "terraform stuff begin"
	  echo "You are working on ${{ env.VAR1 }}"
